runtime: nodejs10
handlers:
  - url: /static/js/(.*)
    static_files: build/static/js/\1
    upload: build/static/js/(.*)
  - url: /static/css/(.*)
    static_files: build/static/css/\1
    upload: build/static/css/(.*)
  - url: /static/media/(.*)
    static_files: build/static/media/\1
    upload: build/static/media/(.*)
  - url: /(.*\.(json|ico))$
    static_files: build/\1
    upload: build/.*\.(json|ico)$
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /login
    static_files: build/index.html
    upload: build/index.html
  - url: /signup
    static_files: build/index.html
    upload: build/index.html
  - url: /groups
    static_files: build/index.html
    upload: build/index.html
  - url: /groups/(*)
    static_files: build/index.html
    upload: build/index.html
  - url: /group-signup
    static_files: build/index.html
    upload: build/index.html
  - url: /analytics
    static_files: build/index.html
    upload: build/index.html
  - url: /new-group
    static_files: build/index.html
    upload: build/index.html
  - url: /contact
    static_files: build/index.html
    upload: build/index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html

    